services:
  blog-db:
    image:  postgres:17
    container_name: "blog-db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
